name: Teste

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: git branch name
        run: |
          echo "Current branch is: ${PR_BRANCH}"
        env:
          PR_BRANCH: ${{ github.head_ref }}

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.5'
          
      - name: run script
        run: python test.py

      - name: commit files
        run: |
          git pull origin ${PR_BRANCH}
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "generate results report" -a
        env:
          PR_BRANCH: ${{ github.head_ref }}
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}  