name: Teste

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: teste
        run: |
          echo "Pull request's base branch is: ${BASE_BRANCH}"
        env:
          BASE_BRANCH: ${{ github.base_ref }}
        if: github.event_name == 'pull_request'
      # - name: checkout repo content
      #   uses: actions/checkout@v2

      # - name: setup python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.8.5'
          
      # - name: run script
      #   run: python test.py

      # - name: commit files
      #   run: |
      #     git pull origin master
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add -A
      #     git commit -m "generate results report" -a
          
      # - name: push changes
      #   uses: ad-m/github-push-action@v0.6.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: master  