name: Teste

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
  
    steps:
      - name: LOL
        with:
          python-version: ${{ matrix.python-version }}
        run: |
          python test.py