name: Teste

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.5'
          
      - name: run script
        run: python sj-gobierno.py